# Generated by Django 6.0.1 on 2026-02-14 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blogpost_slug_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Delivered', 'Delivered'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], default='In Progress', max_length=30)),
                ('tech_stack', models.CharField(blank=True, help_text='Comma separated technologies', max_length=500)),
                ('description', models.TextField(blank=True)),
                ('total_bill', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI'), ('Cash', 'Cash'), ('PayPal', 'PayPal'), ('Cheque', 'Cheque'), ('Other', 'Other')], default='Bank Transfer', max_length=30)),
                ('expenses', models.DecimalField(decimal_places=2, default=0, help_text='Total expenses for this project', max_digits=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_projects', to='core.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
