# Generated by Django 6.0.1 on 2026-02-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactmessage_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_location',
            field=models.CharField(blank=True, help_text='e.g. USA, India', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g. 3 Months', max_length=100),
        ),
    ]
